/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shutthebox;
 
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
 
public class App extends Application {

    private Keyset keyset;
    private Dice dice;
    private RollControl rollControl;
    
    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Hello World!");

        BorderPane root = new BorderPane();

        keyset = new Keyset();
        dice = new Dice();
        rollControl = new RollControl(dice);
        
        root.setTop(keyset.getPane());
        root.setCenter(dice.getPane());
        root.setBottom(rollControl.getPane());

        Scene scene = new Scene(root, 640, 480);
        root.getStylesheets().add("style.css");
        primaryStage.setScene(scene);
        primaryStage.show();
    }
    public static void main(String[] args) {
        launch(args);
    }

}