/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shutthebox;
 
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
 
public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }
    
    @Override
    public void start(Stage primaryStage) {
        primaryStage.setTitle("Hello World!");

        BorderPane root = new BorderPane();
        Keyset keyset = new Keyset();
        root.setTop(keyset.getPane());

        Scene scene = new Scene(root, 640, 480);
        scene.getStylesheets().add("style.css");
        primaryStage.setScene(new Scene(root, 640, 480));
        primaryStage.show();
    }
}
